### ISSUE TITLE
Undefined index

### ISSUE THREAD

**Issue by ghost** [RasmusLindroth/OMDb-PHP-API#3]
There are errors on my site. 

`Notice: Undefined index: Season in E:\programs\xammp2\htdocs\imdb_import\php\omdb.class.php on line 310

Notice: Undefined index: Episode in E:\programs\xammp2\htdocs\imdb_import\php\omdb.class.php on line 310

Notice: Undefined index: seriesID in E:\programs\xammp2\htdocs\imdb_import\php\omdb.class.php on line 310`

**Comment by RasmusLindroth** [comment]
Hello and thank you for the issue!

The bug should be gone in this commit 4adf65b7c87bb1fa84af6e25cd69a9d0601bef6d, and if it's still there please reopen this issue.

**Comment by ghost** [comment]
Works! Thanks a lot!
